# Application States
# TODO: Make this an enum?
STATE_IDLE_DISCONNECTED = 0
STATE_IDLE_CONNECTED = 1
STATE_AWAITING_INPUT = 2
STATE_ERASE_MEM = 3
STATE_READ_MEM = 4
STATE_WRITE_MEM = 5
STATE_UPLOAD_APP = 6
STATE_OPTBYTE_CONFIG = 7
STATE_INVALID = 8
STATE_ANY = 255